#! /bin/bash

# Get the path to the web root folder
webRootPath=`cat ../../install_to`
cd "$webRootPath"

# Move the readme and config files outside of the web root.
mv "./readme.html" "../readme.html"
mv "./wp-config.php" "../wp-config.php"

# Remove the sample configuration file from the web root
rm "./wp-config-sample.php"
